name: Site Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    
jobs:
  site-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Yarn
        working-directory: ./web
        run: npm install --global yarn
      - name: Install dependencies
        working-directory: ./web
        run: yarn
      - name: Site Release
        working-directory: ./web
        run: yarn build && cp -vrf build/* ../ && rm -rf build
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Release ${{ env.GITHUB_REF_NAME }}'
          git push
          git checkout origin/gh-pages
          git merge --no-ff main -m 'Merge Release ${{ env.GITHUB_REF_NAME }}'
          git push

