name: Site Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    
jobs:
  site-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Check Release Version
        run: |
          echo "Check branch main contains the tag:  ${{ github.ref_name }}"
          git pull
          git branch -a --contains " ${{ github.ref_name }}" | egrep '^(. )?main$' || exit 1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Yarn
        working-directory: ./web
        run: npm install --global yarn
      - name: Install dependencies
        working-directory: ./web
        run: yarn
      - name: Site Release
        working-directory: ./web
        run: yarn build && cp -vrf build/* ../ && rm -rf build
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m 'Release  ${{ github.ref_name }}'
          git push

